version: "3.9"

services:
  frontend:
    build: .
    container_name: frontend
    restart: always

    networks:
      - traefik-public

    labels:
      - "traefik.enable=true"

      # роут
      - "traefik.http.routers.frontend.rule=Host(`sesc-it-team.ru`) && PathPrefix(`/auth`)"

      # https
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"

      # внутренний порт контейнера
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

      # убираем /auth перед отправкой в контейнер
      - "traefik.http.middlewares.frontend-strip.stripprefix.prefixes=/auth"
      - "traefik.http.routers.frontend.middlewares=frontend-strip"

networks:
  traefik-public:
    external: true