version: "3.9"

services:
  frontend:
    build: .
    container_name: frontend
    restart: always

    networks:
      - traefik-public

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"

      - "traefik.http.services.frontend-auth.loadbalancer.server.port=3000"

      - "traefik.http.middlewares.frontend-auth-strip.stripprefix.prefixes=/auth"

      - "traefik.http.routers.frontend-auth.rule=Host(`${DOMAIN}`) && (Path(`/auth`) || PathPrefix(`/auth/`))"
      - "traefik.http.routers.frontend-auth.entrypoints=websecure"
      - "traefik.http.routers.frontend-auth.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend-auth.priority=100"
      - "traefik.http.routers.frontend-auth.middlewares=frontend-auth-strip"
      - "traefik.http.routers.frontend-auth.service=frontend-auth"

networks:
  traefik-public:
    external: true